spring.application.name=ExpenseTracker2
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker
spring.datasource.username=root
spring.datasource.password=Yash@2012

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

